// Well-known human proteins with UniProt IDs, names, and descriptions
const PROTEINS = [
  { id: "P01308", name: "Insulin", desc: "Peptide hormone regulating blood glucose levels. Produced by beta cells of the pancreatic islets." },
  { id: "P04637", name: "p53 (TP53)", desc: "Tumor suppressor protein. Guards the genome by inducing cell cycle arrest or apoptosis in response to DNA damage." },
  { id: "P69905", name: "Hemoglobin subunit alpha", desc: "Oxygen-transport protein in red blood cells. Forms a tetramer with two alpha and two beta chains." },
  { id: "P68871", name: "Hemoglobin subunit beta", desc: "Beta chain of hemoglobin. Mutations cause sickle cell disease." },
  { id: "P02768", name: "Serum albumin", desc: "Most abundant protein in blood plasma. Maintains osmotic pressure and transports molecules." },
  { id: "P01023", name: "Alpha-2-macroglobulin", desc: "Large plasma protease inhibitor. Traps and clears proteinases from the bloodstream." },
  { id: "P12277", name: "Creatine kinase B-type", desc: "Enzyme that catalyzes the transfer of phosphate between creatine and ATP in brain and muscle." },
  { id: "P07550", name: "Beta-2 adrenergic receptor", desc: "G protein-coupled receptor. Target of drugs for asthma and heart failure." },
  { id: "P05067", name: "Amyloid-beta precursor (APP)", desc: "Transmembrane protein whose cleavage produces amyloid-beta peptides, central to Alzheimer's disease." },
  { id: "P06213", name: "Insulin receptor", desc: "Receptor tyrosine kinase. Binds insulin to initiate signaling cascades for glucose uptake." },
  { id: "P38398", name: "BRCA1", desc: "DNA repair protein. Mutations dramatically increase breast and ovarian cancer risk." },
  { id: "P51587", name: "BRCA2", desc: "DNA repair protein involved in homologous recombination. Key tumor suppressor." },
  { id: "P04150", name: "Glucocorticoid receptor (NR3C1)", desc: "Nuclear receptor activated by cortisol. Regulates genes involved in metabolism and immunity." },
  { id: "P00533", name: "EGFR", desc: "Epidermal growth factor receptor. Oncogene targeted by multiple cancer drugs." },
  { id: "P08069", name: "IGF-1 receptor", desc: "Receptor for insulin-like growth factor. Promotes cell growth and survival." },
  { id: "P10415", name: "Bcl-2", desc: "Anti-apoptotic protein. Frequently overexpressed in cancers." },
  { id: "P10275", name: "Androgen receptor (AR)", desc: "Nuclear receptor for testosterone. Key in prostate cancer." },
  { id: "P03372", name: "Estrogen receptor alpha (ESR1)", desc: "Nuclear receptor activated by estrogen. Major target in breast cancer therapy." },
  { id: "P01112", name: "HRas", desc: "Small GTPase in the RAS family. Mutations drive many cancers." },
  { id: "P01116", name: "KRas", desc: "GTPase oncogene. Mutated in ~25% of all human cancers." },
  { id: "Q15303", name: "ERBB4", desc: "Receptor tyrosine kinase in the EGFR family. Involved in neural and cardiac development." },
  { id: "P01375", name: "TNF-alpha", desc: "Pro-inflammatory cytokine. Key mediator in immune and inflammatory responses." },
  { id: "P05231", name: "IL-6", desc: "Interleukin-6 cytokine. Central role in inflammation, fever, and acute phase response." },
  { id: "P15692", name: "VEGFA", desc: "Vascular endothelial growth factor. Stimulates blood vessel formation. Anti-cancer target." },
  { id: "P60484", name: "PTEN", desc: "Tumor suppressor phosphatase. Antagonizes PI3K/AKT signaling. Mutated in many cancers." },
  { id: "P42345", name: "mTOR", desc: "Serine/threonine kinase. Master regulator of cell growth, proliferation, and metabolism." },
  { id: "P42574", name: "Caspase-3", desc: "Executioner caspase. Essential protease in the apoptotic cascade." },
  { id: "Q07817", name: "Bcl-xL (BCL2L1)", desc: "Anti-apoptotic Bcl-2 family member. Prevents programmed cell death." },
  { id: "P01584", name: "IL-1 beta", desc: "Pro-inflammatory interleukin. Activated by the inflammasome in innate immunity." },
  { id: "P22001", name: "Voltage-gated potassium channel Kv1.1", desc: "Potassium channel alpha subunit. Critical for neuronal excitability." },
  { id: "P55058", name: "Phospholipid transfer protein (PLTP)", desc: "Transfers phospholipids between lipoproteins in plasma lipid metabolism." },
  { id: "P01579", name: "Interferon gamma (IFNG)", desc: "Key cytokine in Th1 immunity. Activates macrophages and enhances antigen presentation." },
  { id: "P13500", name: "CCL2 (MCP-1)", desc: "Chemokine recruiting monocytes and T cells. Involved in atherosclerosis and inflammation." },
  { id: "P07949", name: "RET proto-oncogene", desc: "Receptor tyrosine kinase. Mutations cause MEN2 and thyroid cancer." },
  { id: "P49841", name: "GSK3-beta", desc: "Glycogen synthase kinase. Key regulator in Wnt signaling, glycogen metabolism, and circadian clock." },
  { id: "P12931", name: "Src kinase (SRC)", desc: "Proto-oncogene tyrosine kinase. First viral oncogene discovered. Regulates cell growth and adhesion." },
  { id: "P31749", name: "AKT1 (Protein kinase B)", desc: "Serine/threonine kinase promoting cell survival and growth. Frequently activated in cancer." },
  { id: "Q04206", name: "NF-kB p65 (RELA)", desc: "Transcription factor subunit. Master regulator of inflammation and immune responses." },
  { id: "P04626", name: "HER2 (ERBB2)", desc: "Receptor tyrosine kinase. Amplified in ~20% of breast cancers. Targeted by trastuzumab." },
  { id: "P01137", name: "TGF-beta-1", desc: "Transforming growth factor beta. Regulates cell proliferation, differentiation, and migration." },
  { id: "P46531", name: "Notch1", desc: "Transmembrane receptor. Notch signaling controls cell fate decisions in development." },
  { id: "P09237", name: "MMP-7 (Matrilysin)", desc: "Matrix metalloproteinase. Degrades extracellular matrix. Implicated in cancer invasion." },
  { id: "P01133", name: "Epidermal growth factor (EGF)", desc: "Growth factor ligand that activates EGFR. Stimulates cell proliferation and differentiation." },
  { id: "P09238", name: "MMP-2 (Gelatinase A)", desc: "Gelatinase that degrades collagen and gelatin. Key in tissue remodeling and metastasis." },
  { id: "P08253", name: "MMP-2 (72kDa)", desc: "Matrix metalloproteinase-2. Critical for extracellular matrix degradation in cancer and inflammation." },
  { id: "P14780", name: "MMP-9 (Gelatinase B)", desc: "Matrix metalloproteinase. Promotes tumor invasion and angiogenesis." },
  { id: "P21802", name: "FGFR2", desc: "Fibroblast growth factor receptor 2. Mutations cause craniosynostosis syndromes." },
  { id: "P11362", name: "FGFR1", desc: "Fibroblast growth factor receptor. Oncogene in multiple cancers when amplified or mutated." },
  { id: "P00747", name: "Plasminogen", desc: "Precursor to plasmin. Degrades fibrin blood clots and extracellular matrix." },
  { id: "P02774", name: "Vitamin D-binding protein (GC)", desc: "Carrier protein for vitamin D metabolites in blood. Also binds actin." },
  { id: "P02775", name: "CXCL7 (Platelet factor 4)", desc: "Chemokine released from platelet alpha granules. Involved in coagulation and inflammation." },
  { id: "P01024", name: "Complement C3", desc: "Central component of the complement system. Opsonizes pathogens for immune clearance." },
  { id: "P01023", name: "Alpha-2-macroglobulin", desc: "Broad-spectrum protease inhibitor in plasma. Also binds growth factors and cytokines." },
  { id: "P07355", name: "Annexin A2", desc: "Calcium-dependent phospholipid-binding protein. Involved in membrane organization and fibrinolysis." },
  { id: "P06744", name: "Glucose-6-phosphate isomerase", desc: "Glycolytic enzyme. Also functions as a cytokine and autoantigen in rheumatoid arthritis." },
  { id: "P11142", name: "Hsc70 (HSPA8)", desc: "Heat shock cognate 71 kDa protein. Essential molecular chaperone in protein folding." },
  { id: "P08238", name: "Hsp90-beta (HSP90AB1)", desc: "Heat shock protein 90. Molecular chaperone stabilizing oncogenic client proteins." },
  { id: "P07900", name: "Hsp90-alpha (HSP90AA1)", desc: "Inducible Hsp90. Folds and stabilizes signaling proteins in stress conditions." },
  { id: "P11021", name: "BiP/GRP78 (HSPA5)", desc: "ER-resident chaperone. Marker of ER stress and the unfolded protein response." },
  { id: "Q15059", name: "BRD3", desc: "Bromodomain protein 3. Reads histone acetylation marks. Emerging cancer drug target." },
  { id: "O60885", name: "BRD4", desc: "Bromodomain protein. Transcriptional regulator targeted by BET inhibitors in cancer." },
  { id: "P35222", name: "Beta-catenin (CTNNB1)", desc: "Wnt pathway effector and cell adhesion molecule. Oncogene when stabilized in cancer." },
  { id: "Q9UHD2", name: "TBK1", desc: "TANK-binding kinase 1. Activates innate immunity via IRF3 and NF-kB." },
  { id: "P01031", name: "Complement C5", desc: "Complement component. Cleavage generates the membrane attack complex." },
  { id: "P02741", name: "C-reactive protein (CRP)", desc: "Acute-phase reactant. Marker of systemic inflammation and cardiovascular risk." },
  { id: "P10909", name: "Clusterin (ApoJ)", desc: "Extracellular chaperone. Involved in apoptosis, lipid transport, and neurodegeneration." },
  { id: "P23229", name: "Integrin alpha-6 (ITGA6)", desc: "Laminin-binding integrin. Mediates cell adhesion to basement membranes." },
  { id: "P05556", name: "Integrin beta-1 (ITGB1)", desc: "Fibronectin receptor beta subunit. Key adhesion molecule in cell-matrix interactions." },
  { id: "P16284", name: "PECAM-1 (CD31)", desc: "Platelet endothelial cell adhesion molecule. Regulates leukocyte transmigration." },
  { id: "P13598", name: "ICAM-2", desc: "Intercellular adhesion molecule. Constitutively expressed on endothelial cells." },
  { id: "P05362", name: "ICAM-1", desc: "Adhesion molecule induced by inflammation. Ligand for LFA-1 on leukocytes." },
  { id: "P35968", name: "VEGFR2 (KDR)", desc: "Primary receptor for VEGF-A. Critical for angiogenesis signaling." },
  { id: "P00734", name: "Prothrombin (F2)", desc: "Coagulation factor II. Converted to thrombin in the clotting cascade." },
  { id: "P00451", name: "Factor VIII", desc: "Blood coagulation factor VIII. Deficiency causes hemophilia A." },
  { id: "P12259", name: "Factor V", desc: "Coagulation factor V. Accelerates prothrombin activation." },
  { id: "P08709", name: "Factor VII", desc: "Initiates the extrinsic coagulation cascade by binding tissue factor." },
  { id: "P13726", name: "Tissue factor (F3)", desc: "Transmembrane glycoprotein. Primary initiator of blood coagulation in vivo." },
  { id: "P05121", name: "PAI-1 (SERPINE1)", desc: "Plasminogen activator inhibitor-1. Regulates fibrinolysis and thrombosis." },
  { id: "P00742", name: "Factor X", desc: "Coagulation factor X. Converts prothrombin to thrombin." },
  { id: "P00748", name: "Factor XII", desc: "Contact activation factor. Initiates the intrinsic coagulation pathway." },
  { id: "P03951", name: "Factor XI", desc: "Coagulation factor XI. Activates factor IX in the intrinsic pathway." },
  { id: "P10144", name: "Granzyme B", desc: "Serine protease in cytotoxic T cells and NK cells. Induces apoptosis in target cells." },
  { id: "P20749", name: "Bcl-3", desc: "Atypical I-kappa-B protein. Regulates NF-kB signaling and cell survival." },
  { id: "Q04759", name: "PKC theta (PRKCQ)", desc: "Protein kinase C theta. Essential for T cell activation and IL-2 production." },
  { id: "P28482", name: "ERK2 (MAPK1)", desc: "Mitogen-activated protein kinase 1. Transduces growth and differentiation signals." },
  { id: "P27361", name: "ERK1 (MAPK3)", desc: "Mitogen-activated protein kinase 3. Activated by MEK in the RAS-RAF-MEK-ERK pathway." },
  { id: "Q16539", name: "p38-alpha MAPK14", desc: "Stress-activated kinase. Mediates inflammatory cytokine production." },
  { id: "P45983", name: "JNK1 (MAPK8)", desc: "c-Jun N-terminal kinase. Activated by stress, cytokines, and DNA damage." },
  { id: "P01100", name: "c-Fos (FOS)", desc: "Immediate early gene product. Forms AP-1 transcription factor with c-Jun." },
  { id: "P05412", name: "c-Jun (JUN)", desc: "Component of AP-1 transcription factor. Regulates proliferation and apoptosis." },
  { id: "P01106", name: "c-Myc (MYC)", desc: "Master transcription factor driving cell growth. Amplified in many cancers." },
  { id: "P04198", name: "N-Myc (MYCN)", desc: "Myc family transcription factor. Amplified in neuroblastoma." },
  { id: "P08047", name: "Sp1", desc: "GC-box binding transcription factor. Regulates housekeeping and inducible genes." },
  { id: "Q09472", name: "p300 (EP300)", desc: "Histone acetyltransferase. Transcriptional coactivator integrating signaling with chromatin." },
  { id: "Q92793", name: "CBP (CREBBP)", desc: "CREB-binding protein. Acetyltransferase coactivator. Mutated in Rubinstein-Taybi syndrome." },
  { id: "P08069", name: "IGF1R", desc: "Insulin-like growth factor 1 receptor. Promotes growth, survival, and anti-apoptotic signaling." }
];
